### ISSUE TITLE
Падение с SIGFPE на тестовых данных

### ISSUE THREAD

**Issue by flyingmutant** [vladnosiv/vk_core_test#1]
Больше деталей сообщить не могу. Если найдете и исправите проблему, отпишитесь здесь, пожалуйста.

**Comment by vladnosiv** [comment]
> Больше деталей сообщить не могу. Если найдете и исправите проблему, отпишитесь здесь, пожалуйста.

Исправил небезопасное деление. Добавил обработку деления на 0 и деления INT64_MIN на -1. Добавлен тест для проверки поведения при делении на ноль.
